/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVC.Vistas.Clientes;

import Frames.FrmRegistroCompleto;
import MVC.Controlador.Controlador;
import MVC.Modelos.Cliente;
import MVC.Vistas.Vista;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joans
 */
public class FrmAdministrar extends javax.swing.JFrame implements Vista<Cliente> {

    private Controlador<Cliente> controlador;
    int yMouse, xMouse;

    /**
     * Creates new form FrmAdministrar
     */
    public FrmAdministrar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.crear1.setVisible(true);
        this.crear2.setVisible(false);
        this.mostrar.setVisible(false);
        this.actualizar.setVisible(false);
        this.eliminar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JPanel();
        minimizeTxt = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        logoG = new javax.swing.JLabel();
        crearBtn = new javax.swing.JPanel();
        lblCrear = new javax.swing.JLabel();
        mostrarBtn = new javax.swing.JPanel();
        lblMostrar = new javax.swing.JLabel();
        actualizarBtn = new javax.swing.JPanel();
        lblActualizar = new javax.swing.JLabel();
        eliminarBtn = new javax.swing.JPanel();
        lblEliminar = new javax.swing.JLabel();
        mostrar = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        title2 = new javax.swing.JLabel();
        logoP2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        lbCopiar = new javax.swing.JLabel();
        crear1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        logoname = new javax.swing.JLabel();
        continuarBtnCrear = new javax.swing.JPanel();
        continuarBtnCrearTxt = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JFormattedTextField();
        cedulaSeparador = new javax.swing.JSeparator();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        nombreSeparador = new javax.swing.JSeparator();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        correoSeparador = new javax.swing.JSeparator();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        fechaSeparador = new javax.swing.JSeparator();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JFormattedTextField();
        numeroSeparado = new javax.swing.JSeparator();
        logoP = new javax.swing.JLabel();
        crear2 = new javax.swing.JPanel();
        logoP1 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        registrarseBtn = new javax.swing.JPanel();
        registrarseBtnTxt = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        nombreSeparador1 = new javax.swing.JSeparator();
        passLabel = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        lblNombre1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        actualizar = new javax.swing.JPanel();
        logoP3 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        txtTelefonoa = new javax.swing.JTextField();
        passLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        modificarBtn = new javax.swing.JPanel();
        modificarBtnTxt = new javax.swing.JLabel();
        newPassLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        confirmNewPassLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txtCedulaa = new javax.swing.JTextField();
        txtNombrea = new javax.swing.JTextField();
        txtEdada = new javax.swing.JTextField();
        confirmNewPassLabel1 = new javax.swing.JLabel();
        confirmNewPassLabel2 = new javax.swing.JLabel();
        txtEmaila = new javax.swing.JTextField();
        confirmNewPassLabel3 = new javax.swing.JLabel();
        txtFechaa = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        eliminar = new javax.swing.JPanel();
        logoP4 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        userLabel2 = new javax.swing.JLabel();
        userTxt1 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        eliminarBtn1 = new javax.swing.JPanel();
        eliminarBtnTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        minimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        minimizeBtn.setPreferredSize(new java.awt.Dimension(40, 40));

        minimizeTxt.setBackground(new java.awt.Color(0, 0, 0));
        minimizeTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        minimizeTxt.setForeground(new java.awt.Color(255, 255, 255));
        minimizeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeTxt.setText("-");
        minimizeTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimizeTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        minimizeTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimizeBtnLayout = new javax.swing.GroupLayout(minimizeBtn);
        minimizeBtn.setLayout(minimizeBtnLayout);
        minimizeBtnLayout.setHorizontalGroup(
            minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(minimizeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        minimizeBtnLayout.setVerticalGroup(
            minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(minimizeBtnLayout.createSequentialGroup()
                    .addComponent(minimizeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        exitBtn.setBackground(new java.awt.Color(0, 0, 0));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("x");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 40));

        menu.setBackground(new java.awt.Color(0, 134, 190));

        logoG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LOGO_PNG.png"))); // NOI18N

        crearBtn.setBackground(new java.awt.Color(0, 134, 190));

        lblCrear.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblCrear.setForeground(new java.awt.Color(255, 255, 255));
        lblCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrear.setText("CREAR");
        lblCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCrearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout crearBtnLayout = new javax.swing.GroupLayout(crearBtn);
        crearBtn.setLayout(crearBtnLayout);
        crearBtnLayout.setHorizontalGroup(
            crearBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        crearBtnLayout.setVerticalGroup(
            crearBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        mostrarBtn.setBackground(new java.awt.Color(0, 134, 190));

        lblMostrar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblMostrar.setForeground(new java.awt.Color(255, 255, 255));
        lblMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrar.setText("MOSTRAR");
        lblMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMostrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMostrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mostrarBtnLayout = new javax.swing.GroupLayout(mostrarBtn);
        mostrarBtn.setLayout(mostrarBtnLayout);
        mostrarBtnLayout.setHorizontalGroup(
            mostrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mostrarBtnLayout.setVerticalGroup(
            mostrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarBtnLayout.createSequentialGroup()
                .addComponent(lblMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        actualizarBtn.setBackground(new java.awt.Color(0, 134, 190));

        lblActualizar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizar.setText("ACTUALIZAR");
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblActualizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout actualizarBtnLayout = new javax.swing.GroupLayout(actualizarBtn);
        actualizarBtn.setLayout(actualizarBtnLayout);
        actualizarBtnLayout.setHorizontalGroup(
            actualizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        actualizarBtnLayout.setVerticalGroup(
            actualizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarBtnLayout.createSequentialGroup()
                .addComponent(lblActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        eliminarBtn.setBackground(new java.awt.Color(0, 134, 190));

        lblEliminar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("ELIMINAR");
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout eliminarBtnLayout = new javax.swing.GroupLayout(eliminarBtn);
        eliminarBtn.setLayout(eliminarBtnLayout);
        eliminarBtnLayout.setHorizontalGroup(
            eliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        eliminarBtnLayout.setVerticalGroup(
            eliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarBtnLayout.createSequentialGroup()
                .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mostrarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoG, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(actualizarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(eliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(logoG, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(crearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mostrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(actualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(eliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 580));

        mostrar.setBackground(new java.awt.Color(255, 255, 255));

        userLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        userLabel.setText("CÉDULA");

        txtBuscador.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscador.setText("Ingrese el numero de cédula");
        txtBuscador.setBorder(null);
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscadorMousePressed(evt);
            }
        });
        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyPressed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        title2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title2.setText("MOSTRAR CLIENTES");

        logoP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LOGO_PEQUEÑO.png"))); // NOI18N

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Cedula", "Nombre", "Fecha Nacimiento", "Email", "Telefono"
            }
        ));
        jScrollPane3.setViewportView(tablaClientes);

        lbCopiar.setBackground(new java.awt.Color(0, 153, 255));
        lbCopiar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lbCopiar.setForeground(new java.awt.Color(51, 153, 255));
        lbCopiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCopiar.setText("COPIAR");
        lbCopiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCopiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCopiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCopiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mostrarLayout = new javax.swing.GroupLayout(mostrar);
        mostrar.setLayout(mostrarLayout);
        mostrarLayout.setHorizontalGroup(
            mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarLayout.createSequentialGroup()
                .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mostrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(mostrarLayout.createSequentialGroup()
                        .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mostrarLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(title2)
                                    .addComponent(userLabel)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logoP2))
                            .addGroup(mostrarLayout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(lbCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 291, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mostrarLayout.setVerticalGroup(
            mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarLayout.createSequentialGroup()
                .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mostrarLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(title2)
                        .addGap(18, 18, 18)
                        .addComponent(userLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mostrarLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(logoP2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lbCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        getContentPane().add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 780, 580));

        crear1.setBackground(new java.awt.Color(255, 255, 255));
        crear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title.setText("REGISTRO CLIENTES");
        crear1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        logoname.setBackground(new java.awt.Color(255, 255, 255));
        logoname.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        logoname.setForeground(new java.awt.Color(255, 255, 255));
        logoname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoname.setText("LICENCIAS");
        crear1.add(logoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 250, 20));

        continuarBtnCrear.setBackground(new java.awt.Color(0, 134, 190));

        continuarBtnCrearTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        continuarBtnCrearTxt.setForeground(new java.awt.Color(255, 255, 255));
        continuarBtnCrearTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continuarBtnCrearTxt.setText("CONTINUAR");
        continuarBtnCrearTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        continuarBtnCrearTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuarBtnCrearTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                continuarBtnCrearTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                continuarBtnCrearTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout continuarBtnCrearLayout = new javax.swing.GroupLayout(continuarBtnCrear);
        continuarBtnCrear.setLayout(continuarBtnCrearLayout);
        continuarBtnCrearLayout.setHorizontalGroup(
            continuarBtnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(continuarBtnCrearTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        continuarBtnCrearLayout.setVerticalGroup(
            continuarBtnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(continuarBtnCrearTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        crear1.add(continuarBtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 310, 40));

        lblCedula.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCedula.setText("NÚMERO DE CÉDULA");
        crear1.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtCedula.setBorder(null);
        txtCedula.setForeground(new java.awt.Color(204, 204, 204));
        txtCedula.setText("Número de cédula");
        txtCedula.setToolTipText("");
        txtCedula.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        crear1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 310, 20));

        cedulaSeparador.setForeground(new java.awt.Color(0, 0, 0));
        crear1.add(cedulaSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 310, 20));

        lblNombre.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblNombre.setText("NOMBRE COMPLETO");
        crear1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Nombre completo");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        crear1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 310, 20));

        nombreSeparador.setForeground(new java.awt.Color(0, 0, 0));
        crear1.add(nombreSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 310, 30));

        lblCorreo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCorreo.setText("CORREO ELECTRÓNICO");
        crear1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.setText("ejemplo@ejemplo.com");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        crear1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 310, 20));

        correoSeparador.setForeground(new java.awt.Color(0, 0, 0));
        crear1.add(correoSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 310, 30));

        lblFecha.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblFecha.setText("FECHA DE NACIMIENTO");
        crear1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        txtFecha.setBorder(null);
        txtFecha.setForeground(new java.awt.Color(204, 204, 204));
        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        txtFecha.setText("yyyy-MM-dd");
        txtFecha.setToolTipText("");
        txtFecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaMousePressed(evt);
            }
        });
        crear1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 310, 20));

        fechaSeparador.setForeground(new java.awt.Color(0, 0, 0));
        crear1.add(fechaSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 310, 20));

        lblNumero.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblNumero.setText("NÚMERO TELEFÓNICO");
        crear1.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        txtNumero.setBorder(null);
        txtNumero.setForeground(new java.awt.Color(204, 204, 204));
        txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtNumero.setText("####-####");
        txtNumero.setToolTipText("");
        txtNumero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroMousePressed(evt);
            }
        });
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        crear1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 310, 20));

        numeroSeparado.setForeground(new java.awt.Color(0, 0, 0));
        crear1.add(numeroSeparado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 310, 20));

        logoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LOGO_PEQUEÑO.png"))); // NOI18N
        crear1.add(logoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 60, 44));

        getContentPane().add(crear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 780, 580));

        crear2.setBackground(new java.awt.Color(255, 255, 255));
        crear2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LOGO_PEQUEÑO.png"))); // NOI18N
        crear2.add(logoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 60, 60));

        title1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title1.setText("REGISTRO OFICIALES");
        crear2.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        registrarseBtn.setBackground(new java.awt.Color(0, 134, 190));

        registrarseBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        registrarseBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        registrarseBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarseBtnTxt.setText("REGISTRARSE");
        registrarseBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registrarseBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarseBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarseBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarseBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout registrarseBtnLayout = new javax.swing.GroupLayout(registrarseBtn);
        registrarseBtn.setLayout(registrarseBtnLayout);
        registrarseBtnLayout.setHorizontalGroup(
            registrarseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrarseBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        registrarseBtnLayout.setVerticalGroup(
            registrarseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrarseBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        crear2.add(registrarseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 310, 40));

        txtNombre1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre1.setText("Nombre usuario");
        txtNombre1.setBorder(null);
        txtNombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombre1MousePressed(evt);
            }
        });
        crear2.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 310, 20));

        nombreSeparador1.setForeground(new java.awt.Color(0, 0, 0));
        crear2.add(nombreSeparador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 310, 30));

        passLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        passLabel.setText("CONTRASEÑA");
        crear2.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        passTxt.setForeground(new java.awt.Color(204, 204, 204));
        passTxt.setText("********");
        passTxt.setBorder(null);
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });
        crear2.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 310, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        crear2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 310, 20));

        lblNombre1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblNombre1.setText("NOMBRE USUARIO");
        crear2.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setText("Para finalizar con su proceso de registro en el\nsistema de Licencias Code, por favor, ingrese\nsu nombre de usuario y contraseña que utilizará\npara ingresar en el perfil de su usuario.\n\nPor su seguridad, le sugerimos que esta \ncontraseña sea lo más segura posible. Evite \nnombres sencillos o fáciles de adivinar. \n\nAl dar click en el botón de \"REGISTRARSE\" solo\npodrá editar su contraseña desde el apartado de \nseguridad. \nPara ello, deberá ingresar su contraseña actual.\nEn caso de no recordar su contraseña actual, deberá\ncontactarse con nuestros asesores.\n");
        jScrollPane1.setViewportView(jTextArea1);

        crear2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 360, 300));

        getContentPane().add(crear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 780, 580));

        actualizar.setBackground(new java.awt.Color(255, 255, 255));
        actualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LOGO_PEQUEÑO.png"))); // NOI18N
        actualizar.add(logoP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        title3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title3.setText("ACTUALIZAR CLIENTE");
        actualizar.add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtTelefonoa.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelefonoa.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefonoa.setBorder(null);
        txtTelefonoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoaMousePressed(evt);
            }
        });
        txtTelefonoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoaActionPerformed(evt);
            }
        });
        actualizar.add(txtTelefonoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 270, 30));

        passLabel1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        passLabel1.setText("2.NOMBRE COMPLETO");
        actualizar.add(passLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        actualizar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 270, 20));

        modificarBtn.setBackground(new java.awt.Color(0, 134, 190));

        modificarBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        modificarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        modificarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificarBtnTxt.setText(" MODIFICAR");
        modificarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout modificarBtnLayout = new javax.swing.GroupLayout(modificarBtn);
        modificarBtn.setLayout(modificarBtnLayout);
        modificarBtnLayout.setHorizontalGroup(
            modificarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        modificarBtnLayout.setVerticalGroup(
            modificarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        actualizar.add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 570, 40));

        newPassLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        newPassLabel.setText("1. CEDULA");
        actualizar.add(newPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        actualizar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 220, 20));

        confirmNewPassLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        confirmNewPassLabel.setText("6.EDAD");
        actualizar.add(confirmNewPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 280, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        actualizar.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 160, 20));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        actualizar.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 20));

        txtCedulaa.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCedulaa.setForeground(new java.awt.Color(204, 204, 204));
        txtCedulaa.setBorder(null);
        txtCedulaa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaaMousePressed(evt);
            }
        });
        txtCedulaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaaActionPerformed(evt);
            }
        });
        actualizar.add(txtCedulaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 30));

        txtNombrea.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombrea.setForeground(new java.awt.Color(204, 204, 204));
        txtNombrea.setBorder(null);
        txtNombrea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreaMousePressed(evt);
            }
        });
        txtNombrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreaActionPerformed(evt);
            }
        });
        actualizar.add(txtNombrea, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 220, 30));

        txtEdada.setEditable(false);
        txtEdada.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEdada.setForeground(new java.awt.Color(204, 204, 204));
        txtEdada.setBorder(null);
        txtEdada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEdadaMousePressed(evt);
            }
        });
        txtEdada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadaActionPerformed(evt);
            }
        });
        actualizar.add(txtEdada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 100, 30));

        confirmNewPassLabel1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        confirmNewPassLabel1.setText("3. EMAIL");
        actualizar.add(confirmNewPassLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 280, -1));

        confirmNewPassLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        confirmNewPassLabel2.setText("4.TELÉFONO");
        actualizar.add(confirmNewPassLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 280, -1));

        txtEmaila.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEmaila.setForeground(new java.awt.Color(204, 204, 204));
        txtEmaila.setBorder(null);
        txtEmaila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmailaMousePressed(evt);
            }
        });
        txtEmaila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailaActionPerformed(evt);
            }
        });
        actualizar.add(txtEmaila, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 270, 30));

        confirmNewPassLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        confirmNewPassLabel3.setText("5.FECHA NACIMIENTO");
        actualizar.add(confirmNewPassLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, -1));

        txtFechaa.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFechaa.setForeground(new java.awt.Color(204, 204, 204));
        txtFechaa.setBorder(null);
        txtFechaa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaaMousePressed(evt);
            }
        });
        txtFechaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaaActionPerformed(evt);
            }
        });
        actualizar.add(txtFechaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 160, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        actualizar.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 270, 20));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        actualizar.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 100, 20));

        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 780, 580));

        eliminar.setBackground(new java.awt.Color(255, 255, 255));
        eliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LOGO_PEQUEÑO.png"))); // NOI18N
        eliminar.add(logoP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        title4.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title4.setText("ELIMINAR CLIENTE");
        eliminar.add(title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        userLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        userLabel2.setText("ID CLIENTE");
        eliminar.add(userLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        userTxt1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        userTxt1.setForeground(new java.awt.Color(204, 204, 204));
        userTxt1.setBorder(null);
        userTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxt1MousePressed(evt);
            }
        });
        userTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxt1ActionPerformed(evt);
            }
        });
        eliminar.add(userTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        eliminar.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 20));

        eliminarBtn1.setBackground(new java.awt.Color(0, 134, 190));

        eliminarBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        eliminarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminarBtnTxt.setText("ELIMINAR");
        eliminarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eliminarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout eliminarBtn1Layout = new javax.swing.GroupLayout(eliminarBtn1);
        eliminarBtn1.setLayout(eliminarBtn1Layout);
        eliminarBtn1Layout.setHorizontalGroup(
            eliminarBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        eliminarBtn1Layout.setVerticalGroup(
            eliminarBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        eliminar.add(eliminarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, 40));

        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 780, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeTxtMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeTxtMouseClicked

    private void minimizeTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeTxtMouseEntered
        minimizeBtn.setBackground(Color.orange);
        minimizeTxt.setForeground(Color.black);
    }//GEN-LAST:event_minimizeTxtMouseEntered

    private void minimizeTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeTxtMouseExited
        minimizeBtn.setBackground(Color.black);
        minimizeTxt.setForeground(Color.white);
    }//GEN-LAST:event_minimizeTxtMouseExited

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.black);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void lblCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearMouseClicked
        crear1.setVisible(true);
        mostrar.setVisible(false);
        actualizar.setVisible(false);
        eliminar.setVisible(false);
        this.controlador.crear(new Cliente());
    }//GEN-LAST:event_lblCrearMouseClicked

    private void lblCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearMouseEntered
        crearBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_lblCrearMouseEntered

    private void lblCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearMouseExited
        crearBtn.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_lblCrearMouseExited

    private void lblMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarMouseClicked
        mostrar.setVisible(true);
        crear1.setVisible(false);
        crear2.setVisible(false);
        actualizar.setVisible(false);
        eliminar.setVisible(false);
        controlador.leer();

    }//GEN-LAST:event_lblMostrarMouseClicked

    private void lblMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarMouseEntered
        mostrarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_lblMostrarMouseEntered

    private void lblMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarMouseExited
        mostrarBtn.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_lblMostrarMouseExited

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
        crear1.setVisible(false);
        crear2.setVisible(false);
        mostrar.setVisible(false);
        actualizar.setVisible(true);
        eliminar.setVisible(false);
        if (controlador.getModelo() != null) {

            txtCedulaa.setText(String.valueOf(controlador.getModelo().getCedula()));
            txtNombrea.setText(controlador.getModelo().getNombreCompleto());
            txtFechaa.setText(controlador.getModelo().getFechaNacimiento());
            txtEmaila.setText(controlador.getModelo().getEmail());
            txtTelefonoa.setText(controlador.getModelo().getTelefono());
            txtEdada.setText(String.valueOf(controlador.getModelo().calcularEdad(this.controlador.getModelo().getFechaNacimiento())));
            txtCedulaa.setForeground(Color.gray);
            txtNombrea.setForeground(Color.gray);
            txtFechaa.setForeground(Color.gray);
            txtEmaila.setForeground(Color.gray);
            txtTelefonoa.setForeground(Color.gray);
            txtEdada.setForeground(Color.gray);
            txtCedulaa.setForeground(Color.gray);
        }
    }//GEN-LAST:event_lblActualizarMouseClicked

    private void lblActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseEntered
        actualizarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_lblActualizarMouseEntered

    private void lblActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseExited
        actualizarBtn.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_lblActualizarMouseExited

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        crear1.setVisible(false);
        crear2.setVisible(false);
        mostrar.setVisible(false);
        actualizar.setVisible(false);
        eliminar.setVisible(true);
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseEntered
        eliminarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_lblEliminarMouseEntered

    private void lblEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseExited
        eliminarBtn.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_lblEliminarMouseExited

    private void continuarBtnCrearTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarBtnCrearTxtMouseClicked
        mostrar.setVisible(false);
        
        
        if (this.txtCedula.getText().equals("Número de cédula") || this.txtCedula.getText().isEmpty() || this.txtCorreo.getText().equals("ejemplo@ejemplo.com")
                || this.txtCorreo.getText().isEmpty() || this.txtFecha.getText().equals("YYYY-MM-DD") || this.txtFecha.getText().isEmpty()
                || this.txtNombre.getText().equals("Nombre completo") || this.txtNombre.getText().isEmpty() || this.txtNumero.getText().equals("####-####") || this.txtNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los espacios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            this.controlador.crear(new Cliente(null, null, null, Integer.parseInt(txtCedula.getText()), txtNombre.getText(), txtFecha.getText(), txtCorreo.getText(), txtNumero.getText()));
JOptionPane.showConfirmDialog(rootPane, "Agredado el cliente con cedula "+txtCedula.getText());
            //AGREGAR ACÁ EL CÓDIGO O MÉTODO PARA ALMACENAR LOS DATOS EN LA BASE DE DATOS//
        }
       
    }//GEN-LAST:event_continuarBtnCrearTxtMouseClicked

    private void continuarBtnCrearTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarBtnCrearTxtMouseEntered
        continuarBtnCrear.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_continuarBtnCrearTxtMouseEntered

    private void continuarBtnCrearTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuarBtnCrearTxtMouseExited
        continuarBtnCrear.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_continuarBtnCrearTxtMouseExited

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        if ("Número de cédula".equals(txtCedula.getText())) {
            txtCedula.setText("");
            txtCedula.setForeground(Color.black);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Nombre completo");
            txtNombre.setForeground(Color.gray);
        }
        if (txtFecha.getText().isEmpty()) {
            txtFecha.setText("YYYY-MM-DD");
            txtFecha.setForeground(Color.gray);
        }
        if (txtNumero.getText().isEmpty()) {
            txtNumero.setText("####-####");
            txtNumero.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("ejemplo@ejemplo.com");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtFecha.getText().isEmpty()) {
            txtFecha.setText("YYYY-MM-DD");
            txtFecha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        if ("Nombre completo".equals(txtNombre.getText())) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if (txtCedula.getText().isEmpty()) {
            txtCedula.setText("Número de cédula");
            txtCedula.setForeground(Color.gray);
        }
        if (txtFecha.getText().isEmpty()) {
            txtFecha.setText("yyyy-MM-dd");
            txtFecha.setForeground(Color.gray);
        }
        if (txtNumero.getText().isEmpty()) {
            txtNumero.setText("####-####");
            txtNumero.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("ejemplo@ejemplo.com");
            txtCorreo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        if ("ejemplo@ejemplo.com".equals(txtCorreo.getText())) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
        if (txtCedula.getText().isEmpty()) {
            txtCedula.setText("Número de cédula");
            txtCedula.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Nombre completo");
            txtNombre.setForeground(Color.gray);
        }
        if (txtFecha.getText().isEmpty()) {
            txtFecha.setText("yyyy-MM-dd");
            txtFecha.setForeground(Color.gray);
        }
        if (txtNumero.getText().isEmpty()) {
            txtNumero.setText("####-####");
            txtNumero.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMousePressed
        if ("yyyy-MM-dd".equals(txtFecha.getText())) {
            txtFecha.setText("");
            txtFecha.setForeground(Color.black);
        }
        if (txtNumero.getText().isEmpty()) {
            txtNumero.setText("####-####");
            txtNumero.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Nombre completo");
            txtNombre.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("ejemplo@ejemplo.com");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtCedula.getText().isEmpty()) {
            txtCedula.setText("Número de cédula");
            txtCedula.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtFechaMousePressed

    private void txtNumeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMousePressed
        if ("####-####".equals(txtNumero.getText())) {
            txtNumero.setText("");
            txtNumero.setForeground(Color.black);
        }
        if (txtCedula.getText().isEmpty()) {
            txtCedula.setText("Número de cédula");
            txtCedula.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("ejemplo@ejemplo.com");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Nombre completo");
            txtNombre.setForeground(Color.gray);
        }
        if (txtFecha.getText().isEmpty()) {
            txtFecha.setText("yyyy-MM-dd");
            txtFecha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNumeroMousePressed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void registrarseBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseBtnTxtMouseClicked
//        if (this.txtNombre.getText().equals("Nombre usuario") || this.txtNombre.getText().isEmpty() || this.passTxt.getPassword().equals("********")) {
//            JOptionPane.showMessageDialog(null, "Debe llenar todos los espacios", "ERROR", JOptionPane.ERROR_MESSAGE);
//        } else {
        FrmRegistroCompleto frm = new FrmRegistroCompleto();
        frm.setVisible(true);
        JOptionPane.showMessageDialog(null, "PRUEBA", "PRUEBA", JOptionPane.INFORMATION_MESSAGE);
        //AGREGAR ACÁ EL CÓDIGO O MÉTODO PARA ALMACENAR LOS DATOS//
//        }
    }//GEN-LAST:event_registrarseBtnTxtMouseClicked

    private void registrarseBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseBtnTxtMouseEntered
        registrarseBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_registrarseBtnTxtMouseEntered

    private void registrarseBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseBtnTxtMouseExited
        registrarseBtn.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_registrarseBtnTxtMouseExited

    private void txtNombre1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombre1MousePressed
        if ("Nombre usuario".equals(txtNombre.getText())) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if (String.valueOf(passTxt.getPassword()).isEmpty()) {
            passTxt.setText("********");
            passTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombre1MousePressed

    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
        if (String.valueOf(passTxt.getPassword()).equals("********")) {
            passTxt.setText("");
            passTxt.setForeground(Color.black);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Nombre usuario");
            txtNombre.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passTxtMousePressed

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void txtTelefonoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoaMousePressed
        if (txtTelefonoa.getText().equals("Ingrese su nombre de usuario")) {
            txtTelefonoa.setText("");
            txtTelefonoa.setForeground(Color.black);
        }
        if (String.valueOf(passTxt.getPassword()).isEmpty()) {
            passTxt.setText("********");
            passTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtTelefonoaMousePressed

    private void txtTelefonoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoaActionPerformed

    private void modificarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtnTxtMouseClicked
        JOptionPane.showMessageDialog(null, "PRUEBA", "PRUEBA", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_modificarBtnTxtMouseClicked

    private void modificarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtnTxtMouseEntered
        modificarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_modificarBtnTxtMouseEntered

    private void modificarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtnTxtMouseExited
        modificarBtn.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_modificarBtnTxtMouseExited

    private void userTxt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxt1MousePressed
        if (txtTelefonoa.getText().equals("Ingrese su nombre de usuario")) {
            txtTelefonoa.setText("");
            txtTelefonoa.setForeground(Color.black);
        }
        if (String.valueOf(passTxt.getPassword()).isEmpty()) {
            passTxt.setText("********");
            passTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_userTxt1MousePressed

    private void userTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt1ActionPerformed

    private void eliminarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnTxtMouseClicked
        //CODIGO PARA ELIMINAR EL USUARIO
        this.controlador.borrar();
        JOptionPane.showMessageDialog(null, "PRUEBA", "PRUEBA", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_eliminarBtnTxtMouseClicked

    private void eliminarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnTxtMouseEntered
        eliminarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_eliminarBtnTxtMouseEntered

    private void eliminarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnTxtMouseExited
        eliminarBtn.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_eliminarBtnTxtMouseExited

    private void txtBuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            controlador.leer("%" + txtBuscador.getText() + "%");
        }
    }//GEN-LAST:event_txtBuscadorKeyPressed

    private void txtBuscadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMousePressed
        if (txtBuscador.getText().equals("Ingrese el numero de cédula")) {
            txtBuscador.setText("");
            txtBuscador.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtBuscadorMousePressed

    private void txtCedulaaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaaMousePressed

    private void txtCedulaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaaActionPerformed

    private void txtNombreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreaMousePressed

    private void txtNombreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreaActionPerformed

    private void txtEdadaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEdadaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadaMousePressed

    private void txtEdadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadaActionPerformed

    private void txtEmailaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailaMousePressed

    private void txtEmailaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailaActionPerformed

    private void txtFechaaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaaMousePressed

    private void txtFechaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaaActionPerformed

    private void lbCopiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCopiarMouseClicked
        if (this.tablaClientes.getRowCount() > 0 && tablaClientes.getSelectedRow() > -1) {
            Cliente cliente = new Cliente(Integer.parseInt(String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 0))), null, null, Integer.parseInt(String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 1))), String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 2)), String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 3)), String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 4)), String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 5)));
            controlador.setModelo(cliente);

        }
    }//GEN-LAST:event_lbCopiarMouseClicked

    private void lbCopiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCopiarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbCopiarMouseEntered

    private void lbCopiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCopiarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbCopiarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actualizar;
    private javax.swing.JPanel actualizarBtn;
    private javax.swing.JSeparator cedulaSeparador;
    private javax.swing.JLabel confirmNewPassLabel;
    private javax.swing.JLabel confirmNewPassLabel1;
    private javax.swing.JLabel confirmNewPassLabel2;
    private javax.swing.JLabel confirmNewPassLabel3;
    private javax.swing.JPanel continuarBtnCrear;
    private javax.swing.JLabel continuarBtnCrearTxt;
    private javax.swing.JSeparator correoSeparador;
    private javax.swing.JPanel crear1;
    private javax.swing.JPanel crear2;
    private javax.swing.JPanel crearBtn;
    private javax.swing.JPanel eliminar;
    private javax.swing.JPanel eliminarBtn;
    private javax.swing.JPanel eliminarBtn1;
    private javax.swing.JLabel eliminarBtnTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JSeparator fechaSeparador;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbCopiar;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCrear;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel logoG;
    private javax.swing.JLabel logoP;
    private javax.swing.JLabel logoP1;
    private javax.swing.JLabel logoP2;
    private javax.swing.JLabel logoP3;
    private javax.swing.JLabel logoP4;
    private javax.swing.JLabel logoname;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel minimizeBtn;
    private javax.swing.JLabel minimizeTxt;
    private javax.swing.JPanel modificarBtn;
    private javax.swing.JLabel modificarBtnTxt;
    private javax.swing.JPanel mostrar;
    private javax.swing.JPanel mostrarBtn;
    private javax.swing.JLabel newPassLabel;
    private javax.swing.JSeparator nombreSeparador;
    private javax.swing.JSeparator nombreSeparador1;
    private javax.swing.JSeparator numeroSeparado;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passLabel1;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JPanel registrarseBtn;
    private javax.swing.JLabel registrarseBtnTxt;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JFormattedTextField txtCedula;
    private javax.swing.JTextField txtCedulaa;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdada;
    private javax.swing.JTextField txtEmaila;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtFechaa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombrea;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JTextField txtTelefonoa;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userLabel2;
    private javax.swing.JTextField userTxt1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    @Override
    public void mostarDato() {
        DefaultTableModel table = (DefaultTableModel) tablaClientes.getModel();
        table.setRowCount(0);
        if (controlador.getLista() != null) {
            Iterator<Cliente> iterator = controlador.getLista().iterator();
            while (iterator.hasNext()) {
                Cliente cliente = iterator.next();
                table.addRow(new Object[]{cliente.getIdCliente(), cliente.getCedula(), cliente.getNombreCompleto(), cliente.getFechaNacimiento(), cliente.getEmail(), cliente.getTelefono()});
                //cliente.getId(),cliente.getCedula(),cliente.getNombreCompleto(),cliente.getTelefono(),cliente.getEmail(),cliente.getFechaNacimiento()
            }
        }
        tablaClientes.setModel(table);
    }

    @Override
    public void mostarMensaje(String msg, int messageType) {
    }
}
